/**
 * SF Symbol → @expo/vector-icons mapping.
 *
 * The app was ported from SwiftUI, so call sites use SF Symbol names
 * (`Image(systemName:)`). SF Symbols are Apple-only and render nothing on
 * Android, so the shared Icon component resolves each name through this table to
 * a cross-platform glyph (MaterialCommunityIcons `mci`, Ionicons `ion`,
 * MaterialIcons `mat`, or FontAwesome `fa`). Every glyph here is validated
 * against the family's glyphmap (see scripts/validate-icon-map).
 *
 * Names flagged `// ~approx` are the closest available match, not an exact
 * equivalent — worth an eyeball on device.
 */

export type IconFamily = 'mci' | 'ion' | 'mat' | 'fa';

/** SF Symbol name → [family, glyph name in that family]. */
export const ICON_MAP: Record<string, [IconFamily, string]> = {
  'apple.logo': ['mci', 'apple'],
  'apps.iphone': ['mci', 'cellphone'], // ~approx
  'arrow.clockwise.circle.fill': ['ion', 'refresh-circle'],
  'arrow.down.circle.fill': ['ion', 'arrow-down-circle'],
  'arrow.down.message.fill': ['mci', 'message-arrow-left'], // ~approx (received)
  'arrow.right': ['mci', 'arrow-right'],
  'arrow.right.circle.fill': ['ion', 'arrow-forward-circle'],
  'arrow.triangle.2.circlepath': ['mci', 'sync'],
  'arrow.triangle.2.circlepath.circle.fill': ['mci', 'sync-circle'],
  'arrow.turn.up.right': ['mci', 'arrow-top-right'], // ~approx
  'arrow.up.arrow.down': ['mci', 'swap-vertical'],
  'arrow.up.circle.fill': ['ion', 'arrow-up-circle'],
  'arrow.up.forward.circle.fill': ['mci', 'arrow-top-right-thick'], // ~approx
  'arrow.up.left.and.arrow.down.right': ['mci', 'arrow-expand'],
  'arrow.up.message.fill': ['mci', 'message-arrow-right'], // ~approx (sent)
  'arrow.up.right': ['mci', 'arrow-top-right'],
  'arrow.up.right.square': ['mci', 'open-in-new'],
  'arrow.up.right.square.fill': ['mci', 'open-in-new'],
  'arrow.uturn.left.circle': ['mci', 'undo'], // ~approx
  'bag': ['ion', 'bag-outline'],
  'bag.fill': ['ion', 'bag'],
  'banknote.fill': ['mci', 'cash'],
  'barcode.viewfinder': ['mci', 'barcode-scan'],
  'bell.badge.fill': ['mci', 'bell-badge'],
  'bell.fill': ['mci', 'bell'],
  'bell.slash.fill': ['mci', 'bell-off'],
  'bolt.fill': ['mci', 'lightning-bolt'],
  'box.truck.fill': ['mci', 'truck'],
  'brain': ['mci', 'brain'],
  'brain.head.profile.fill': ['mci', 'brain'], // ~approx
  'briefcase.fill': ['mci', 'briefcase'],
  'bubble.left.and.bubble.right': ['mci', 'chat-outline'],
  'bubble.left.and.bubble.right.fill': ['mci', 'chat'],
  'bubble.left.and.text.bubble.right': ['mci', 'forum-outline'],
  'bubble.left.and.text.bubble.right.fill': ['mci', 'forum'],
  'bubble.left.fill': ['mci', 'chat'],
  'building.2.fill': ['mci', 'office-building'],
  'building.columns.fill': ['mci', 'bank'],
  'calendar': ['mci', 'calendar'],
  'calendar.badge.checkmark': ['mci', 'calendar-check'],
  'calendar.badge.clock': ['mci', 'calendar-clock'],
  'calendar.badge.exclamationmark': ['mci', 'calendar-alert'],
  'calendar.badge.plus': ['mci', 'calendar-plus'],
  'calendar.day.timeline.left': ['mci', 'calendar-range'], // ~approx
  'camera.fill': ['mci', 'camera'],
  'car.fill': ['mci', 'car'],
  'cart': ['mci', 'cart-outline'],
  'cart.badge.plus': ['mci', 'cart-plus'],
  'cart.fill': ['mci', 'cart'],
  'chart.bar.fill': ['mci', 'chart-bar'],
  'chart.bar.xaxis.ascending': ['mci', 'chart-bar'], // ~approx
  'chart.line.uptrend.xyaxis': ['mci', 'chart-line'],
  'checkmark': ['mci', 'check'],
  'circle': ['mci', 'circle-outline'], // unselected state (paired with checkmark.circle.fill)
  'checkmark.circle': ['mci', 'check-circle-outline'],
  'checkmark.circle.fill': ['mci', 'check-circle'],
  'checkmark.seal.fill': ['mci', 'check-decagram'],
  'checkmark.shield.fill': ['mci', 'shield-check'],
  'chevron.down': ['mci', 'chevron-down'],
  'chevron.left': ['mci', 'chevron-left'],
  'chevron.right': ['mci', 'chevron-right'],
  'chevron.right.circle.fill': ['mci', 'chevron-right-circle'],
  'chevron.up': ['mci', 'chevron-up'],
  'chevron.up.chevron.down': ['mci', 'unfold-more-horizontal'],
  'clock': ['mci', 'clock-outline'],
  'clock.arrow.circlepath': ['mci', 'history'],
  'clock.badge': ['mci', 'clock-alert-outline'], // ~approx
  'clock.badge.xmark': ['mci', 'clock-remove-outline'],
  'clock.fill': ['mci', 'clock'],
  'creditcard': ['mci', 'credit-card-outline'],
  'creditcard.fill': ['mci', 'credit-card'],
  'cross.case.fill': ['mci', 'medical-bag'],
  'cube.box.fill': ['mci', 'cube'],
  'delete.left.fill': ['mci', 'backspace'],
  'doc.on.doc': ['mci', 'content-copy'],
  'doc.plaintext.fill': ['mci', 'file-document'],
  'doc.richtext.fill': ['mci', 'file-document-outline'], // ~approx
  'doc.text.below.ecg': ['mci', 'file-chart'], // ~approx
  'doc.text.fill': ['mci', 'file-document'],
  'doc.text.magnifyingglass': ['mci', 'file-search'],
  'dollarsign': ['mci', 'currency-usd'],
  'dollarsign.arrow.circlepath': ['mci', 'cash-refund'], // ~approx
  'dollarsign.circle': ['mci', 'currency-usd'], // ~approx (no circled-dollar glyph)
  'dollarsign.circle.fill': ['mci', 'currency-usd'], // ~approx (no circled-dollar glyph)
  'ellipsis.circle': ['mci', 'dots-horizontal-circle-outline'],
  'ellipsis.circle.fill': ['mci', 'dots-horizontal-circle'],
  'envelope.fill': ['mci', 'email'],
  'exclamationmark.circle.fill': ['mci', 'alert-circle'],
  'exclamationmark.shield.fill': ['mci', 'shield-alert'],
  'exclamationmark.triangle.fill': ['mci', 'alert'],
  'eye.fill': ['mci', 'eye'],
  'eye.slash.fill': ['mci', 'eye-off'],
  'fork.knife': ['mci', 'silverware-fork-knife'],
  'function': ['mci', 'function-variant'],
  'g.circle.fill': ['mci', 'google'], // ~approx (Google)
  'gear': ['mci', 'cog-outline'],
  'gearshape.fill': ['mci', 'cog'],
  'gift.fill': ['mci', 'gift'],
  'giftcard.fill': ['mci', 'wallet-giftcard'],
  'globe': ['mci', 'web'],
  'hammer.fill': ['mci', 'hammer'],
  'hand.raised.fill': ['mci', 'hand-back-right'], // ~approx
  'hand.thumbsup.fill': ['mci', 'thumb-up'],
  'heart.fill': ['mci', 'heart'],
  'hourglass': ['mci', 'timer-sand'],
  'house.fill': ['mci', 'home'],
  'info.circle': ['mci', 'information-outline'],
  'info.circle.fill': ['mci', 'information'],
  'iphone': ['mci', 'cellphone'],
  'key.fill': ['mci', 'key'],
  'keyboard': ['mci', 'keyboard-outline'],
  'laptopcomputer': ['mci', 'laptop'],
  'lightbulb.fill': ['mci', 'lightbulb-on'],
  'line.3.horizontal': ['mci', 'menu'],
  'link': ['mci', 'link-variant'],
  'link.circle.fill': ['mci', 'link-box-variant'], // ~approx
  'list.bullet.rectangle': ['mci', 'format-list-bulleted'],
  'list.bullet.rectangle.fill': ['mci', 'format-list-bulleted'],
  'list.bullet.rectangle.portrait.fill': ['mci', 'format-list-bulleted'],
  'list.clipboard.fill': ['mci', 'clipboard-list'],
  'list.number': ['mci', 'format-list-numbered'],
  'location.fill': ['mci', 'map-marker'],
  'location.slash': ['mci', 'map-marker-off'],
  'lock.doc.fill': ['mci', 'file-lock'],
  'lock.fill': ['mci', 'lock'],
  'lock.shield.fill': ['mci', 'shield-lock'],
  'magnifyingglass': ['mci', 'magnify'],
  'mappin.and.ellipse': ['mci', 'map-marker-radius'],
  'mappin.circle.fill': ['mci', 'map-marker'],
  'megaphone.fill': ['mci', 'bullhorn'],
  'message.badge.filled.fill': ['mci', 'message-badge'],
  'message.fill': ['mci', 'message-text'],
  'minus': ['mci', 'minus'],
  'minus.circle': ['mci', 'minus-circle-outline'],
  'minus.circle.fill': ['mci', 'minus-circle'],
  'moon.fill': ['mci', 'weather-night'],
  'moon.zzz.fill': ['mci', 'sleep'],
  'note.text': ['mci', 'note-text'],
  'number.square.fill': ['mci', 'numeric'],
  'paintbrush.fill': ['mci', 'brush'],
  'paintpalette.fill': ['mci', 'palette'],
  'paperplane.fill': ['mci', 'send'],
  'pencil': ['mci', 'pencil'],
  'percent': ['mci', 'percent'],
  'person.2': ['mci', 'account-multiple-outline'],
  'person.2.badge.gearshape.fill': ['mci', 'account-cog'],
  'person.2.fill': ['mci', 'account-multiple'],
  'person.2.slash': ['mci', 'account-multiple-remove'], // ~approx
  'person.3.fill': ['mci', 'account-group'],
  'person.badge.key.fill': ['mci', 'account-key'],
  'person.badge.plus': ['mci', 'account-plus'],
  'person.circle.fill': ['mci', 'account-circle'],
  'person.crop.circle': ['mci', 'account-circle-outline'],
  'person.crop.circle.badge.checkmark': ['mci', 'account-check'],
  'person.crop.circle.badge.exclamationmark.fill': ['mci', 'account-alert'],
  'person.crop.circle.badge.plus': ['mci', 'account-plus'],
  'person.crop.circle.badge.xmark': ['mci', 'account-remove'],
  'person.crop.rectangle.fill': ['mci', 'card-account-details'], // ~approx
  'person.fill': ['mci', 'account'],
  'person.fill.xmark': ['mci', 'account-off'],
  'person.slash': ['mci', 'account-off'],
  'phone.badge.plus': ['mci', 'phone-plus'],
  'phone.fill': ['mci', 'phone'],
  'plus': ['mci', 'plus'],
  'plus.circle.fill': ['mci', 'plus-circle'],
  'qrcode': ['mci', 'qrcode'],
  'qrcode.viewfinder': ['mci', 'qrcode-scan'],
  'questionmark.circle': ['mci', 'help-circle-outline'],
  'questionmark.circle.fill': ['mci', 'help-circle'],
  'rectangle.portrait.and.arrow.right': ['mci', 'logout'],
  'repeat': ['mci', 'repeat'],
  'scissors': ['mci', 'content-cut'],
  'scissors.circle': ['mci', 'content-cut'],
  'scissors.circle.fill': ['mci', 'content-cut'],
  'shield.checkered': ['mci', 'shield-check'], // ~approx
  'shield.fill': ['mci', 'shield'],
  'shippingbox': ['mci', 'package-variant-closed'],
  'shippingbox.fill': ['mci', 'package-variant'],
  'slider.horizontal.3': ['mci', 'tune'],
  'sparkles': ['mci', 'star-four-points'],
  'square.and.arrow.down': ['mci', 'tray-arrow-down'],
  'square.and.arrow.down.fill': ['mci', 'tray-arrow-down'],
  'square.and.arrow.down.on.square': ['mci', 'import'],
  'square.and.arrow.up': ['mci', 'share-variant'],
  'square.and.arrow.up.fill': ['mci', 'share-variant'],
  'square.and.pencil': ['mci', 'square-edit-outline'],
  'square.on.square': ['mci', 'content-duplicate'],
  'star': ['mci', 'star-outline'], // unselected/empty star (paired with star.fill)
  'star.fill': ['mci', 'star'],
  'storefront': ['mci', 'storefront-outline'],
  'storefront.fill': ['mci', 'storefront'],
  'sun.max': ['mci', 'white-balance-sunny'],
  'sun.max.fill': ['mci', 'white-balance-sunny'],
  'tablecells': ['mci', 'table'],
  'tag.fill': ['mci', 'tag'],
  'text.alignleft': ['mci', 'format-align-left'],
  'text.bubble.fill': ['mci', 'message-text'],
  'text.quote': ['mci', 'format-quote-close'],
  'textformat': ['mci', 'format-size'],
  'timer': ['mci', 'timer-outline'],
  'trash': ['mci', 'trash-can-outline'],
  'trash.fill': ['mci', 'trash-can'],
  'tray': ['mci', 'tray'],
  'wallet.pass.fill': ['mci', 'wallet'],
  'wand.and.stars': ['mci', 'auto-fix'],
  'wave.3.right': ['mci', 'access-point'], // ~approx (broadcast)
  'wifi.slash': ['mci', 'wifi-off'],
  'wrench.and.screwdriver.fill': ['mci', 'tools'],
  'xmark': ['mci', 'close'],
  'xmark.circle.fill': ['mci', 'close-circle'],
};
